---
title: "Final Project - SK4.1"
author: "Sarah Im" 
output: html_document
date: "2024-12-04"
---

## Do voters want Republicans or Democrats in Congress? 

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Loading required libraries
library(tidyr)
library(janitor)
library(ggplot2)
library(dplyr)
```
### Importing and Cleaning Raw Data for the analysis of the Democratic Party 
```{r echo=FALSE, message=FALSE, warning=FALSE}
ballot.data <- read.csv("data/generic_polllist (1).csv")

ballot.Approve <- ballot.data %>%
  clean_names() %>%
  select(startdate, dem) %>%
  na.omit()

ballot.Approve$startdate <- as.Date(ballot.Approve$startdate, format = "%m/%d/%Y")
origin_date <- as.Date("11/21/2020", format = "%m/%d/%Y")
ballot.Approve$days_since_origin <- as.numeric(ballot.Approve$startdate - origin_date)

ballot.Approve
```
### Further converted data set format for easier plotting 

```{r echo=FALSE, message=FALSE, warning=FALSE}
ballot.Approve
ballot.wide <- pivot_wider(ballot.Approve, names_from = startdate, values_from = dem, values_fn=mean) 
ballot.wide

ballot.long <- pivot_longer(ballot.wide, cols = !days_since_origin, names_to = "startdate", values_to = "dem")
```


### Properly Formatted Data was plotted using ggplot 

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.cap = "Figure 1. Plot of Approval Rating from Polls vs. Days Since Origin of polls. Plot demonstrates the change in approval ratings of the democratic party in congress over time since the origin of the polls on 11/21/20. The democratic party experienced a mean approval rating of around 43.9% with the range being approximately 11.3% (min. value = 38.3%, highest value=50.0%) from 11/21/20 to 11/05/2022."}

vis1 <- ggplot(ballot.long, aes(x=days_since_origin, y=dem)) + geom_point(color = "blue", pch=19, alpha=0.5) + labs(x = "Days Since Origin of Polls (11/21/20)", y = "Approval Rating from Polls (%)", title = "Approval of Democratic Party in Congress Over Time") + theme_minimal() + theme(plot.title = element_text(hjust = 0.5)) + ylim(35,50)
vis1
```

### Cleaning Raw Data for the analysis of the Republican Party 

```{r echo=FALSE, message=FALSE, warning=FALSE}
ballot.Approve2 <- ballot.data %>%
  clean_names() %>%
  select(startdate, rep) %>%
  na.omit()

ballot.Approve2$startdate <- as.Date(ballot.Approve2$startdate, format = "%m/%d/%Y")
origin_date <- as.Date("11/21/2020", format = "%m/%d/%Y")
ballot.Approve2$days_since_origin <- as.numeric(ballot.Approve2$startdate - origin_date)
ballot.Approve2
```


### Further converted data set format for easier plotting 

```{r echo=FALSE, message=FALSE, warning=FALSE}
ballot.Approve2
ballot.wide2 <- pivot_wider(ballot.Approve2, names_from = startdate, values_from = rep, values_fn=mean) 
ballot.long2 <- pivot_longer(ballot.wide2, cols = !days_since_origin, names_to = "startdate", values_to = "rep") 
```